name: Rust

on:
  push:
    branches: [ "buil-test" ]
  pull_request:
    branches: [ "buil-test" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  macos-check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: cargo test --all-features
  ubuntu-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: cargo test --all-features
  windows-check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: cargo test --all-features