name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build for Ubuntu
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux-binary
          path: target/x86_64-unknown-linux-gnu/release/your_app

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Linux artifact
        uses: actions/download-artifact@v2
        with:
          name: linux-binary

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build for macOS
        run: cargo build --release --target x86_64-apple-darwin

      - name: Build for Windows
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Archive macOS artifact
        uses: actions/upload-artifact@v2
        with:
          name: mac-binary
          path: target/x86_64-apple-darwin/release/your_app

      - name: Archive Windows artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-binary
          path: target/x86_64-pc-windows-msvc/release/your_app
